#+TITLE: Example
#+LATEX_CLASS: dnd
#+LATEX_HEADER: \usepackage{lipsum}
#+OPTIONS: bg:full justified:nil toc:nil

* Chapter 1: The Dark \LaTeX

** Main Section
\lipsum[2]

#+BEGIN_QUOTEBOX
As you approach this template you get a sense that the blood and tears of many generations went into its making. A warm feeling welcomes you as you type your first words.
#+END_QUOTEBOX

*** Fun with boxes
**** Even more fun!

#+NAME: This Is a Comment Box!
#+BEGIN_COMMENTBOX
A =commentbox= is a box for minimal highlighting of text. It lacks the ornamentation of =paperbox=, but it can handle being broken over a column.
#+END_COMMENTBOX

#+BEGIN_SUBTITLE
Weapon, +1, +2, or +3
Weapon (any), uncommon (+1), rare (+2), or very rare (+3)
#+END_SUBTITLE
# Need a subtitle

\lipsum[3]

#+NAME: Behold, the Paperbox!
#+BEGIN_PAPERBOX
The =paperbox= is used as a sidebar. It does not break over columns and is best used with a figure environment to float it to one corner of the page where the surrounding text can then flow around it.
#+END_PAPERBOX

#+HEADER: Nice Table
| *Table head* | *Table head* |
| Some value | Some value |
| Some value | Some value |
| Some value | Some value |

** Spells

#+NAME: Beautiful Typesetting
#+ATTR_SPELL: :level 4 :school illusion :range 5 feet :cast 1 action :duration Until dispelled :comp S, M (ink and parchment, which the spell consumes)
#+BEGIN_SPELL
You are able to transform a written message of any length into a beautiful
scroll. All creatures within range that can see the scroll must make a wisdom
saving throw or be charmed by you until the spell ends.

While the creature is charmed by you, they cannot take their eyes off the
scroll and cannot willingly move away from the scroll. Also, the targets can
make a wisdom saving throw at the end of each of their turns. On a success,
they are no longer charmed.
#+END_SPELL

\lipsum[2]

#+NAME: Monster Foo
#+ATTR_MONSTER_INFO: :size medium :race metasyntactic variable :subrace goblinoid :alignment neutral evil
#+ATTR_MONSTER_BASICS: :ac 9 (12 with \emph{mage armor}) :hp 3d8+3 :speed 30 :fly 30
#+ATTR_MONSTER_STATS: :str 12 :dex 8 :con 13 :int 10 :wis 14 :cha 15
#+ATTR_MONSTER_DETAILS: :langs Common, Goblin :senses darkvision 60ft., passive Perception 10 :cr 1
#+BEGIN_MONSTER
- Innate Spellcasting :: Foo's spellcasting ability is Charisma (spell save DC 12, +4 to hit with spell attacks). It can innately cast the following spells, requiring no material components:
  - At will :: /misty step/
  - 3/day :: /fog cloud/, /rope trick/
  - 1/day :: /identify/
- Spellcasting :: Foo is a 3rd-level spellcaster. Its spellcasting ability is Charisma (spell save DC 12, +4 to hit with spell attacks). It has the following sorcerer spells prepared:
  - At will :: /blade ward/, /fire bolt/, /light/, /shocking grasp/
  - 1st level (4 slots) :: /burning hands/, /mage armor/
  - 2nd level (2 slots) :: /scorching ray/
- Actions
  - Multiattack :: The foo makes two melee attacks.
  - Dagger :: /Melee or Ranged Weapon Attack:/ +3 to hit, reach 5 ft. or range 20/60ft., one target. /Hit:/ \dice{1d4 + 1} piercing damage.
  - Flame Tongue Longsword :: /Melee Weapon Attack:/ +3 to hit, reach 5 ft., one target. /Hit:/ \dice{1d4 + 1} slashing damage plus \dice{2d6} fire damage, or \dice{1d10 + 1} slashing damage plus \dice{2d6} fire damage if used with two hands.
  - Assassin's Light Crossbow :: /Ranged Weapon Attack:/ +0 to hit, range 80/320 ft., one target. /Hit:/ \dice{1d8} piercing damage, and the target must make a DC 15 Constitution saving throw, taking \dice{7d6} poison damage on a failed save, or half as much damage on a successful one.
#+END_MONSTER

** Colors

This package provides several global color variables to style =commentbox=, =quotebox=, =paperbox=, and =dndtable= environments.

#+ATTR_DND: :align lX
| *Color*           | *Description*                                |
| =commentboxcolor= | Controls =commentbox= background.            |
| =paperboxcolor=   | Controls =paperbox= background.              |
| =quoteboxcolor=   | Controls =quotebox= background.              |
| =tablecolor=      | Controls background of even =dndtable= rows. |

See Table [[tab:colors]] for a list of accent colors that match the core books.

#+NAME: tab:colors
#+CAPTION: Colors supported by this package
#+ATTR_DND: :align XX
| *Color*                         | *Description*                    |
| =PhbLightGreen=                 | Light green used in PHB Part 1   |
| =PhbLightCyan=                  | Light cyan used in PHB Part 2    |
| =PhbMauve=                      | Pale purple used in PHB Part 3   |
| =PhbTan=                        | Light brown used in PHB appendix |
| =DmgLavender=                   | Pale purple used in DMG Part 1   |
| =DmgCoral=                      | Orange-pink used in DMG Part 2   |
| =DmgSlateGray= (=DmgSlateGrey=) | Blue-gray used in PHB Part 3     |
| =DmgLilac=                      | Purple-gray used in DMG appendix |

- Use =\setthemecolor[<color>]= to set =themecolor=, =commentcolor=, =paperboxcolor=, and =tablecolor= to a specific color.
- Calling =\setthemecolor= without an argument sets those colors to the current =themecolor=.
- =commentbox=, =dndtable=, =paperbox=, and =quoteboxcolor= also accept an optional color argument to set the color for a single instance.

*** Examples

**** Using =themecolor=

#+BEGIN_SRC org :exports none
  \setthemecolor[PhbMauve]

  ,#+NAME: Example
  ,#+BEGIN_PAPERBOX
  \lipsum[2]
  ,#+END_PAPERBOX

  \setthemecolor[PhbLightCyan]

  ,#+HEADER: Example
  ,#+ATTR_DND: :align cX
  | *d8* | *Item*                  |
  |  1   | Small wooden button     |
  |  2   | Red feather             |
  |  3   | Human tooth             |
  |  4   | Vial of green liquid    |
  |  6   | Tasty biscuit           |
  |  7   | Broken axe handle       |
  |  8   | Tarnished silver locket |
#+END_SRC

\setthemecolor[PhbMauve]

#+NAME: Example
#+BEGIN_PAPERBOX
\lipsum[2]
#+END_PAPERBOX

\setthemecolor[PhbLightCyan]

#+HEADER: Example
#+ATTR_DND: :align cX
| *d8* | *Item*                  |
|    1 | Small wooden button     |
|    2 | Red feather             |
|    3 | Human tooth             |
|    4 | Vial of green liquid    |
|    6 | Tasty biscuit           |
|    7 | Broken axe handle       |
|    8 | Tarnished silver locket |

**** Using element color arguments

#+BEGIN_SRC org :exports none
  ,#+ATTR_DND: :align cX :color DmgCoral
  | *d8* | *Item*                  |
  |  1   | Small wooden button     |
  |  2   | Red feather             |
  |  3   | Human tooth             |
  |  4   | Vial of green liquid    |
  |  6   | Tasty biscuit           |
  |  7   | Broken axe handle       |
  |  8   | Tarnished silver locket |
#+END_SRC

#+ATTR_DND: :align cX :color DmgCoral
| *d8* | *Item*                  |
|    1 | Small wooden button     |
|    2 | Red feather             |
|    3 | Human tooth             |
|    4 | Vial of green liquid    |
|    6 | Tasty biscuit           |
|    7 | Broken axe handle       |
|    8 | Tarnished silver locket |

** Map Regions :map:

The map region commands provides automatic numbering of areas.

#+BEGIN_SRC org
,** Map Regions :map:

,*** Village of Hommlet

This is the village of hommlet.

,**** Inn of the Welcome Wench

Inside the village is the inn of the
Welcome Wench.

,**** Blacksmith's Forge

There's a blacksmith in town, too.

,*** Foo's Castle

This is foo's home, a hovel of mud and
sticks.

,**** Moat

This ditch has a board spanning it.

,**** Entrance

A five-foot hole reveals the dirt floor
illuminated by a hole in the roof.
#+END_SRC

*** Village of Hommlet

This is the village of hommlet.

**** Inn of the Welcome Wench

Inside the village is the inn of the Welcome Wench.

**** Blacksmith's Forge

There's a blacksmith in town, too.

*** Foo's Castle

This is foo's home, a hovel of mud and sticks.

**** Moat

This ditch has a board spanning it.

**** Entrance

A five-foot hole reveals the dirt floor illuminated by a hole in the roof.
